{"kind":"symbol","identifier":{"url":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:8TinkLink0A11ErrorReasonO","text":"TinkErrorReason","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO","text":"AuthenticationErrorType"},{"text":")","kind":"text"}],"modules":[{"name":"TinkLink"}],"title":"TinkError.ErrorStatus.authenticationError(_:)","externalID":"s:8TinkLink0A5ErrorV0C6StatusO014authenticationC0yAeA0aC6ReasonO014AuthenticationC4TypeOcAEmF","role":"symbol","roleHeading":"Case"},"abstract":[{"type":"text","text":"The error occurred during the authentication process with the bank."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authenticationError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TinkErrorReason","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO"},{"kind":"text","text":"."},{"preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO","text":"AuthenticationErrorType","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/TinkLink\/documentation\/TinkLink","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus"]]},"sections":[],"references":{"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus/authenticationError(_:)":{"abstract":[{"text":"The error occurred during the authentication process with the bank.","type":"text"}],"url":"\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)","kind":"symbol","title":"TinkError.ErrorStatus.authenticationError(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authenticationError","kind":"identifier"},{"kind":"text","text":"("},{"text":"TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO","text":"AuthenticationErrorType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)"},"doc://TinkLink/documentation/TinkLink":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink","title":"TinkLink","type":"topic","url":"\/documentation\/tinklink","role":"collection"},"doc://TinkLink/documentation/TinkLink/TinkErrorReason":{"abstract":[{"text":"The error reason that describes the cause of the error.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TinkErrorReason","kind":"identifier"}],"url":"\/documentation\/tinklink\/tinkerrorreason","kind":"symbol","title":"TinkErrorReason","role":"symbol","navigatorTitle":[{"text":"TinkErrorReason","kind":"identifier"}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","type":"topic"},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationErrorType","kind":"identifier"}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","navigatorTitle":[{"text":"AuthenticationErrorType","kind":"identifier"}],"url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype","kind":"symbol","type":"topic","abstract":[{"text":"The error occurred during the authentication process with the bank.","type":"text"}],"role":"symbol","title":"TinkErrorReason.AuthenticationErrorType"},"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus":{"url":"\/documentation\/tinklink\/tinkerror\/errorstatus","navigatorTitle":[{"text":"ErrorStatus","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The error status describes the category for the error that occurred.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ErrorStatus","kind":"identifier"}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus","title":"TinkError.ErrorStatus","kind":"symbol"},"doc://TinkLink/documentation/TinkLink/TinkError":{"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","role":"symbol","title":"TinkError","abstract":[{"type":"text","text":"An error returned by Tink service requests when something went wrong."}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TinkError","kind":"identifier"}],"navigatorTitle":[{"text":"TinkError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/tinklink\/tinkerror"}}}