{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO","text":"TinkErrorReason"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO","text":"AuthenticationErrorType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The error occurred during the authentication process with the bank."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthenticationErrorType","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO"},{"kind":"text","text":")"}],"title":"TinkError.ErrorStatus.authenticationError(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:8TinkLink0A5ErrorV0C6StatusO014authenticationC0yAeA0aC6ReasonO014AuthenticationC4TypeOcAEmF","modules":[{"name":"TinkLink"}]},"hierarchy":{"paths":[["doc:\/\/TinkLink\/documentation\/TinkLink","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus"]]},"references":{"doc://TinkLink/documentation/TinkLink/TinkErrorReason":{"role":"symbol","title":"TinkErrorReason","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TinkErrorReason"}],"abstract":[{"type":"text","text":"The error reason that describes the cause of the error."}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TinkErrorReason"}],"url":"\/documentation\/tinklink\/tinkerrorreason"},"doc://TinkLink/documentation/TinkLink/TinkError":{"role":"symbol","title":"TinkError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TinkError"}],"abstract":[{"type":"text","text":"An error returned by Tink service requests when something went wrong."}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TinkError"}],"url":"\/documentation\/tinklink\/tinkerror"},"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus/authenticationError(_:)":{"role":"symbol","title":"TinkError.ErrorStatus.authenticationError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TinkErrorReason","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthenticationErrorType","preciseIdentifier":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The error occurred during the authentication process with the bank."}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus\/authenticationError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/tinklink\/tinkerror\/errorstatus\/authenticationerror(_:)"},"doc://TinkLink/documentation/TinkLink":{"role":"collection","title":"TinkLink","abstract":[],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink","kind":"symbol","type":"topic","url":"\/documentation\/tinklink"},"doc://TinkLink/documentation/TinkLink/TinkError/ErrorStatus":{"role":"symbol","title":"TinkError.ErrorStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorStatus"}],"abstract":[{"type":"text","text":"The error status describes the category for the error that occurred."}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkError\/ErrorStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorStatus"}],"url":"\/documentation\/tinklink\/tinkerror\/errorstatus"},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType":{"role":"symbol","title":"TinkErrorReason.AuthenticationErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationErrorType"}],"abstract":[{"type":"text","text":"The error occurred during the authentication process with the bank."}],"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorType"}],"url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype"}}}