{"sections":[],"metadata":{"title":"TinkErrorReason.AuthenticationErrorType.TinkSideError.unknownError","externalID":"s:8TinkLink0A11ErrorReasonO014AuthenticationC4TypeO0a4SideC0O07unknownC0yA2GmF","role":"symbol","symbolKind":"case","modules":[{"name":"TinkLink"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}]},"identifier":{"url":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType\/TinkSideError\/unknownError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/TinkLink\/documentation\/TinkLink","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType","doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType\/TinkSideError"]]},"abstract":[{"type":"text","text":"Unknown unexpected error on Tink side."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype\/tinksideerror\/unknownerror"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://TinkLink/documentation/TinkLink/TinkErrorReason":{"type":"topic","kind":"symbol","title":"TinkErrorReason","url":"\/documentation\/tinklink\/tinkerrorreason","abstract":[{"text":"The error reason that describes the cause of the error.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TinkErrorReason"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TinkErrorReason"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason"},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType/TinkSideError":{"type":"topic","kind":"symbol","title":"TinkErrorReason.AuthenticationErrorType.TinkSideError","url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype\/tinksideerror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TinkSideError"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TinkSideError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType\/TinkSideError"},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType/TinkSideError/unknownError":{"identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType\/TinkSideError\/unknownError","url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype\/tinksideerror\/unknownerror","type":"topic","abstract":[{"type":"text","text":"Unknown unexpected error on Tink side."}],"kind":"symbol","title":"TinkErrorReason.AuthenticationErrorType.TinkSideError.unknownError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"role":"symbol"},"doc://TinkLink/documentation/TinkLink":{"kind":"symbol","title":"TinkLink","type":"topic","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink","url":"\/documentation\/tinklink","role":"collection","abstract":[]},"doc://TinkLink/documentation/TinkLink/TinkErrorReason/AuthenticationErrorType":{"type":"topic","kind":"symbol","title":"TinkErrorReason.AuthenticationErrorType","url":"\/documentation\/tinklink\/tinkerrorreason\/authenticationerrortype","abstract":[{"text":"The error occurred during the authentication process with the bank.","type":"text"}],"navigatorTitle":[{"text":"AuthenticationErrorType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationErrorType"}],"role":"symbol","identifier":"doc:\/\/TinkLink\/documentation\/TinkLink\/TinkErrorReason\/AuthenticationErrorType"}}}